using System.Text.Json;
using System.Text.Json.Serialization;
using Cairn.Api.Contracts;
using Cairn.Domain;

namespace Cairn.Acceptance.Contract;

/// <summary>
/// The request half of the contract. <see cref="ApiContractTests"/> pins what the server
/// sends; this pins what it accepts.
///
/// The gap this closes is real: the Angular client's service specs asserted request bodies
/// against hand-written expectations, so a fabricated request model and a fabricated spec
/// agreed with each other and both were wrong. Binding both sides to one recorded artifact is
/// the only thing that breaks that circularity.
///
/// These entries are generated by serialising the actual C# request records through the API's
/// own serializer settings — never hand-typed, because a hand-typed expectation is just
/// another fake. To regenerate after a deliberate contract change:
///
///     CAIRN_RECORD_CONTRACT=1 dotnet test --filter FullyQualifiedName~RequestContract
///
/// then retarget the TypeScript models until `npm run test:contract` passes again.
/// </summary>
public class RequestContractTests
{
    /// <summary>
    /// Mirrors Program.cs: ASP.NET's web defaults (camelCase) plus the string enum converter.
    /// If those ever diverge, every request shape here is a lie.
    /// </summary>
    private static readonly JsonSerializerOptions ApiJson = BuildApiJson();

    private static JsonSerializerOptions BuildApiJson()
    {
        var options = new JsonSerializerOptions(JsonSerializerDefaults.Web);
        options.Converters.Add(new JsonStringEnumConverter());
        return options;
    }

    /// <summary>
    /// One representative instance per request record. Values are illustrative; only the
    /// shape is contract. Nullable members are populated so they appear in the recording —
    /// System.Text.Json omits nothing by default here, but an explicitly null member would
    /// still serialise, and the client needs to know the field exists.
    /// </summary>
    private static readonly (string Entry, object Body)[] Requests =
    [
        ("POST /api/auth/sign-in -> request (SignInRequest)",
            new SignInRequest("admin@faithtech.to", "correct-horse-battery")),

        ("POST /api/auth/register -> request (RegisterRequest)",
            new RegisterRequest("lead@faithtech.to", "A Lead", "correct-horse-battery")),

        ("POST /api/auth/refresh -> request (RefreshRequest)",
            new RefreshRequest("a-raw-refresh-token")),

        ("POST /api/ideas -> request (CreateIdeaRequest)",
            new CreateIdeaRequest(
                "Run a Build Night in September",
                "Does this seem like a good idea?",
                ResponseType.Options,
                DateTimeOffset.Parse("2026-07-16T12:00:00+00:00"),
                DateTimeOffset.Parse("2026-07-23T12:00:00+00:00"),
                ["First choice", "Second choice"])),

        ("PUT /api/ideas/{id} -> request (UpdateIdeaRequest)",
            new UpdateIdeaRequest(
                "Run a Build Night in September",
                "Does this seem like a good idea?",
                ResponseType.Options,
                DateTimeOffset.Parse("2026-07-16T12:00:00+00:00"),
                DateTimeOffset.Parse("2026-07-23T12:00:00+00:00"),
                ["First choice", "Second choice"])),

        // Exactly one of the three is ever set; all three are part of the shape. The server
        // reads the response type from the idea, so the client never states it.
        ("PUT /api/ideas/{id}/votes -> request (CastVoteRequest)",
            new CastVoteRequest(null, Guid.Empty, null)),

        ("POST /api/ideas/{id}/comments -> request (AddCommentRequest)",
            new AddCommentRequest("A comment from a lead.")),

        ("POST /api/vote-sessions -> request (RedeemVoteLinkRequest)",
            new RedeemVoteLinkRequest("a-raw-magic-link-token")),

        // Empty or omitted userIds means every lead.
        ("POST /api/ideas/{id}/vote-links -> request (CreateVoteLinksRequest)",
            new CreateVoteLinksRequest([Guid.Empty]))
    ];

    private static string RecordingPath()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !Directory.Exists(Path.Combine(directory.FullName, "frontend")))
        {
            directory = directory.Parent;
        }

        return Path.Combine(
            directory?.FullName ?? throw new InvalidOperationException("Could not locate the repo root."),
            "frontend", "e2e", "fixtures", "recorded-api-contract.json");
    }

    private static string[] KeysOf(JsonElement element) =>
        element.EnumerateObject().Select(p => p.Name).OrderBy(n => n).ToArray();

    [Fact]
    public void Request_bodies_still_match_the_recording()
    {
        var path = RecordingPath();
        using var document = JsonDocument.Parse(File.ReadAllText(path));

        if (Environment.GetEnvironmentVariable("CAIRN_RECORD_CONTRACT") == "1")
        {
            Regenerate(path, document);
            return;
        }

        var failures = new List<string>();

        foreach (var (entry, body) in Requests)
        {
            var actual = KeysOf(JsonSerializer.SerializeToElement(body, body.GetType(), ApiJson));

            if (!document.RootElement.TryGetProperty(entry, out var recorded))
            {
                failures.Add($"'{entry}' is missing from the recording.");
                continue;
            }

            var expected = KeysOf(recorded);
            if (!expected.SequenceEqual(actual))
            {
                failures.Add(
                    $"'{entry}'\n    recorded: {string.Join(", ", expected)}\n    actual:   {string.Join(", ", actual)}");
            }
        }

        Assert.True(failures.Count == 0,
            $"""
             Request contracts drifted from the recording, so the TypeScript request models
             built against it are now wrong:

             {string.Join("\n\n", failures)}

             If the change is intended, regenerate:
                 CAIRN_RECORD_CONTRACT=1 dotnet test --filter FullyQualifiedName~RequestContract
             then retarget the models. Do not hand-edit the JSON.
             """);
    }

    private static void Regenerate(string path, JsonDocument existing)
    {
        // Preserve every existing entry and its order; append or overwrite request entries.
        var merged = new Dictionary<string, JsonElement>();
        foreach (var property in existing.RootElement.EnumerateObject())
        {
            merged[property.Name] = property.Value.Clone();
        }

        foreach (var (entry, body) in Requests)
        {
            merged[entry] = JsonSerializer.SerializeToElement(body, body.GetType(), ApiJson);
        }

        var json = JsonSerializer.Serialize(merged, new JsonSerializerOptions
        {
            WriteIndented = true,
            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
        });

        File.WriteAllText(path, json);
    }
}
